### ISSUE TITLE
매뉴얼 목록 화면 디자인

### ISSUE THREAD

**Issue by taiji202** [jinbonetwork/the-art-of-protest-ios#6]
![photo245816135745906640](https://cloud.githubusercontent.com/assets/5800448/10445715/1e9048fe-71b1-11e5-96fd-903c1afe00ce.jpg)

분홍색으로 체크한 border 다 빼주세욘

**Comment by han0ah** [comment]
f918908da71828cf572e4d05ff2098f44cd66a1d 해결함
