### ISSUE TITLE
정보 화면 디자인 변경

### ISSUE THREAD

**Issue by taiji202** [jinbonetwork/the-art-of-protest-ios#7]
![credit](https://cloud.githubusercontent.com/assets/5800448/10445729/4e700d8e-71b1-11e5-905f-0602f8f50eb5.png)

안드로이드 개발, 이란 긴 레이블이 빠지니까 양쪽이 균형이 안 맞아서요. 미안하지만 정렬 좀 바꿔 주세요...;;

**Comment by han0ah** [comment]
afa045761f949ecccbd6f07469cdd6dd587c6edf 해결함
